# notch and bandpass filtering and z-normalization
apply_notch: true
notch_freqs: [50.0, 100.0]
apply_bandpass: true
bandpass_l_freq: 0.3
bandpass_h_freq: 30.0
apply_resample: false
resample_freq: null
apply_znorm: true
apply_per_night_znorm: false  # epoch-wise z-normalization