# notch and bandpass filtering, and resampling
apply_notch: true
notch_freqs: [50.0, 100.0]
apply_bandpass: true
bandpass_l_freq: 0.5
bandpass_h_freq: 40.0
apply_resample: true
resample_freq: 128.0
apply_znorm: false
znorm_per_channel: true