# notch and bandpass filtering
apply_notch: true
notch_freqs: [50.0, 100.0]
apply_bandpass: true
bandpass_l_freq: 0.5
bandpass_h_freq: 40.0
apply_resample: false
resample_freq: null
apply_znorm: false
znorm_per_channel: true